# Changes here will be overwritten by Copier
_commit: v0.1.5
_src_path: gh://ninanor/python-template
author_name: ninanor
debug: false
default_branch_name: main
docker: true
email: niccolo.cantu@nina.no
notebook: false
project_name: DWCA-parquet-api
project_slug: dwca_parquet
repo_name: dwca_parquet
repo_org: ninanor
template_type: python
type_annotations: false
