services:
  app:
    build:
      context: .
    environment:
      DEBUG: True
    ports:
      - 8000:8000
    command: uv run fastapi dev src/dwca_parquet/main.py
    #command: uv run pdb -c continue main.py
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
